"use client"

import { useState } from "react"
import { GalleryFilter } from "@/components/sections/gallery-filter"
import { GalleryGrid } from "@/components/sections/gallery-grid"
import { CategoryDescriptions } from "@/components/sections/gallery-descriptions"

interface GalleryItem {
  id: number
  title: string
  image: string
  type: "image" | "video"
  rotation?: number
  scale?: number
  zIndex?: number
}

const galleryData: Record<string, GalleryItem[]> = {
  "SCOAN HQ": [
    {
      id: 1,
      title: "SCOAN Headquarters Service",
      image: "/scoanhq/1.jpg",
      type: "image",
      rotation: -8,
      scale: 0.85,
      zIndex: 1,
    },
    {
      id: 2,
      title: "Sunday Service",
      image: "/scoanhq/2.jpg",
      type: "image",
      rotation: -4,
      scale: 0.9,
      zIndex: 2,
    },
    {
      id: 3,
      title: "Prayer Session",
      image: "/scoanhq/3.jpg",
      type: "image",
      rotation: 0,
      scale: 1,
      zIndex: 30,
    },
  ],
  "Ghana": [
    {
      id: 4,
      title: "Revival Meeting 2025",
      image: "/ghanapix/1.jpg",
      type: "image",
      rotation: 4,
      scale: 0.9,
      zIndex: 3,
    },
    {
      id: 5,
      title: "Revival Meeting 2025",
      image: "/ghanapix/2.jpg",
      type: "image",
      rotation: 8,
      scale: 0.85,
      zIndex: 30,
    },
    {
      id: 6,
      title: "Kumasi Ministry",
      image: "/ghanapix/3.jpg",
      type: "image",
      rotation: 8,
      scale: 0.85,
      zIndex: 1,
    },
    {
      id: 7,
      title: "Kumasi Ministry",
      image: "/ghanapix/4.jpg",
      type: "image",
      rotation: 8,
      scale: 0.85,
      zIndex: 1,
    },
    {
      id: 8,
      title: "Kumasi Ministry",
      image: "/ghanapix/5.jpg",
      type: "image",
      rotation: 8,
      scale: 0.85,
      zIndex: 1,
    },
    {
      id: 9,
      title: "Kumasi Ministry",
      image: "/ghanapix/6.jpg",
      type: "image",
      rotation: 8,
      scale: 0.85,
      zIndex: 1,
    },
    {
      id: 10, 
      title: "Kumasi Ministry",
      image: "/ghanapix/7.jpg",
      type: "image",
      rotation: 8,
      scale: 0.85,
      zIndex: 1,
    },
    {
      id: 11,
      title: "Kumasi Ministry",
      image: "/ghanapix/8.jpg",
      type: "image",
      rotation: 8,
      scale: 0.85,
      zIndex: 1,
    },
    {
      id: 12,
      title: "Kumasi Ministry",
      image: "/ghanapix/9.jpg",
      type: "image",
      rotation: 8,
      scale: 0.85,
      zIndex: 1,
    },
    {
      id: 13,
      title: "Kumasi Ministry",
      image: "/ghanapix/10.jpg",
      type: "image",
      rotation: 8,
      scale: 0.85,
      zIndex: 1,
    },
    {
      id: 14,
      title: "Kumasi Ministry",
      image: "/ghanapix/11.jpg",
      type: "image",
      rotation: 8,
      scale: 0.85,
      zIndex: 1,
    },
    {
      id: 15,
      title: "Kumasi Ministry",
      image: "/ghanapix/12.jpg",
      type: "image",
      rotation: 8,
      scale: 0.85,
      zIndex: 1,
    },
    {
      id: 16,
      title: "Kumasi Ministry",
      image: "/ghanapix/13.jpg",
      type: "image",
      rotation: 8,
      scale: 0.85,
      zIndex: 1,
    },
    {
      id: 17,
      title: "Kumasi Ministry",
      image: "/ghanapix/14.jpg",
      type: "image",
      rotation: 8,
      scale: 0.85,
      zIndex: 1,
    },
    {
      id: 18,
      title: "Kumasi Ministry",
      image: "/ghanapix/15.jpg",  
      type: "image",
      rotation: 8,
      scale: 0.85,
      zIndex: 1,
    },
    {
      id: 19,
      title: "Kumasi Ministry",
      image: "/ghanapix/16.jpg",
      type: "image",
      rotation: 8,
      scale: 0.85,
      zIndex: 1,
    },
    {
      id: 20,
      title: "Kumasi Ministry",
      image: "/ghanapix/17.jpg",
      type: "image",
      rotation: 8,
      scale: 0.85,
      zIndex: 1,
    },
    {
      id: 21,
      title: "Kumasi Ministry",
      image: "/ghanapix/18.jpg",
      type: "image",
      rotation: 8,
      scale: 0.85,
      zIndex: 1,
    },
    {
      id: 22,
      title: "Kumasi Ministry",
      image: "/ghanapix/19.jpg",
      type: "image",
      rotation: 8,
      scale: 0.85,
      zIndex: 1,
    },
  ],
  "Kenya": [
    {
      id: 23,
      title: "",
      image: "/kenya/1.jpg",
      type: "image",
      rotation: -6,
      scale: 0.88,
      zIndex: 2,
    },
    {
      id: 24,
      title: "",
      image: "/kenya/2.jpg",
      type: "image",
      rotation: 2,
      scale: 0.92,
      zIndex: 1,
    },
    {
      id: 25,
      title: "",
      image: "/kenya/3.jpg",
      type: "image",
      rotation: 0,
      scale: 1,
      zIndex: 30,
    },
    {
      id: 26,
      title: "",
      image: "/kenya/4.jpg",
      type: "image",
      rotation: 0,
      scale: 1,
      zIndex: 30,
    },
    {
      id: 27,
      title: "",
      image: "/kenya/5.jpg",
      type: "image",
      rotation: 0,
      scale: 1,
      zIndex: 30,
    },
    {
      id: 28,
      title: "",
      image: "/kenya/6.jpg",
      type: "image",
      rotation: 0,
      scale: 1,
      zIndex: 30,
    },
    {
      id: 29,
      title: "",
      image: "/kenya/7.jpg",
      type: "image",
      rotation: 0,
      scale: 1,
      zIndex: 30,
    },
    {
      id: 30,
      title: "",
      image: "/kenya/8.jpg",
      type: "image",
      rotation: 0,
      scale: 1,
      zIndex: 30,
    },
    {
      id: 31,
      title: "",
      image: "/kenya/9.jpg",
      type: "image",
      rotation: 0,
      scale: 1,
      zIndex: 30,
    },
    {
      id: 32,
      title: "",
      image: "/kenya/10.jpg",
      type: "image",
      rotation: 0,
      scale: 1,
      zIndex: 30,
    },
    {
      id: 33,
      title: "",
      image: "/kenya/11.jpg",
      type: "image",
      rotation: 0,
      scale: 1,
      zIndex: 30,
    },
    {
      id: 34,
      title: "",
      image: "/kenya/12.jpg",
      type: "image",
      rotation: 0,
      scale: 1,
      zIndex: 30,
    },
    {
      id: 35,
      title: "",
      image: "/kenya/13.jpg",
      type: "image",
      rotation: 0,
      scale: 1,
      zIndex: 30,
    },
    {
      id: 36,
      title: "",
      image: "/kenya/14.jpg",
      type: "image",
      rotation: 0,
      scale: 1,
      zIndex: 30,
    },
    {
      id: 37, 
      title: "",
      image: "/kenya/15.jpg",
      type: "image",
      rotation: 0,
      scale: 1,
      zIndex: 30,
    },
    {
      id: 38,
      title: "",
      image: "/kenya/16.jpg",
      type: "image",
      rotation: 0,
      scale: 1,
      zIndex: 30,
    },
    {
      id: 39,
      title: "",
      image: "/kenya/17.jpg",
      type: "image",
      rotation: 0,
      scale: 1,
      zIndex: 30,
    },
    {
      id: 40,
      title: "",
      image: "/kenya/18.jpg",
      type: "image",
      rotation: 0,
      scale: 1,
      zIndex: 30,
    },
    {
      id: 41,
      title: "",
      image: "/kenya/19.jpg",
      type: "image",
      rotation: 0,
      scale: 1,
      zIndex: 30, 
    },
  ],
  "Lagos": [
    {
      id: 42,
      title: "",
      image: "/lagos/1.jpg",
      type: "image",
      rotation: -4,
      scale: 0.9,
      zIndex: 3,
    },
    {
      id: 43,
      title: "Victoria Island Service",
      image: "/lagos/2.jpg",
      type: "image",
      rotation: 6,
      scale: 0.87,
      zIndex: 1,
    },
    {
      id: 44,
      title: "Ikeja Outreach",
      image: "/lagos/3.jpg",
      type: "image",
      rotation: 0,
      scale: 1,
      zIndex: 30,
    },
    {
      id: 45,
      title: "",
      image: "/lagos/4.jpg",
      type: "image",
      rotation: 0,
      scale: 1,
      zIndex: 30,
    },
    {
      id: 46,
      title: "",
      image: "/lagos/5.jpg",
      type: "image",
      rotation: 0,
      scale: 1,
      zIndex: 30,
    },
    {
      id: 47, 
      title: "",
      image: "/lagos/6.jpg",
      type: "image",
      rotation: 0,
      scale: 1,
      zIndex: 30,
    },
    {
      id: 48,
      title: "",
      image: "/lagos/7.jpg",
      type: "image",
      rotation: 0,
      scale: 1,
      zIndex: 30,
    },
    {
      id: 49,
      title: "",
      image: "/lagos/8.jpg",
      type: "image",
      rotation: 0,
      scale: 1,
      zIndex: 30,
    },
    {
      id: 50,
      title: "",
      image: "/lagos/9.jpg",
      type: "image",
      rotation: 0,
      scale: 1,
      zIndex: 30,
    },
    {
      id: 51,
      title: "",
      image: "/lagos/10.jpg",
      type: "image",
      rotation: 0,
      scale: 1,
      zIndex: 30,
    },
    {
      id: 52,
      title: "",
      image: "/lagos/11.jpg",
      type: "image",
      rotation: 0,
      scale: 1,
      zIndex: 30,
    },
    {
      id: 53,
      title: "",
      image: "/lagos/12.jpg",
      type: "image",
      rotation: 0,
      scale: 1,
      zIndex: 30,
    },
  ],
 "South Africa":[
    {
      id: 54,
      title: "Cape Town Crusade",
      image: "/southafrica/1.jpg",
      type: "image",
      rotation: -6,
      scale: 0.88,
      zIndex: 2,
    },
    {
      id: 55,
      title: "Johannesburg Ministry",
      image: "/southafrica/2.jpg",
      type: "image",
      rotation: 6,
      scale: 0.87,
      zIndex: 1,
    },
    {
      id: 56,
      title: "",
      image: "/southafrica/3.jpg",
      type: "image",
      rotation: 6,
      scale: 0.87,
      zIndex: 1,
    },
    {
      id: 57,
      title: "",
      image: "/southafrica/4.jpg",
      type: "image",
      rotation: 6,
      scale: 0.87,
      zIndex: 1,
    },
    {
      id: 58,
      title: "",
      image: "/southafrica/5.jpg",
      type: "image",
      rotation: 6,
      scale: 0.87,
      zIndex: 1,
    },
    {
      id: 59,
      title: "",
      image: "/southafrica/6.jpg",
      type: "image",
      rotation: 6,
      scale: 0.87,
      zIndex: 1,
    },
    {
      id: 60,
      title: "",
      image: "/southafrica/7.jpg",
      type: "image",
      rotation: 6,
      scale: 0.87,
      zIndex: 1,
    },
    {
      id: 61,
      title: "",
      image: "/southafrica/8.jpg",
      type: "image",
      rotation: 6,
      scale: 0.87,
      zIndex: 1,
    },
    {
      id: 62,
      title: "",
      image: "/southafrica/9.jpg",
      type: "image",
      rotation: 6,
      scale: 0.87,
      zIndex: 1,
    },
    {
      id: 63,
      title: "",
      image: "/southafrica/10.jpg",
      type: "image",
      rotation: 6,
      scale: 0.87,
      zIndex: 1,
    },
    {
      id: 64, 
      title: "",
      image: "/southafrica/11.jpg",
      type: "image",
      rotation: 6,
      scale: 0.87,
      zIndex: 1,
    },
    {
      id: 65,
      title: "",
      image: "/southafrica/12.jpg",
      type: "image",
      rotation: 6,
      scale: 0.87,
      zIndex: 1,
    },
    {
      id: 66,
      title: "",
      image: "/southafrica/13.jpg",
      type: "image",
      rotation: 6,
      scale: 0.87,
      zIndex: 1,
    },
  ],
  "Argentina": [
    {
      id: 67,
      title: "Argentina Crusade Day 1",
      image: "/argentina/day1-2.jpg",
      type: "image",
      rotation: -4,
      scale: 0.9,
      zIndex: 3,
    },
    {
      id: 68,
      title: "Argentina Crusade Day 1",
      image: "/argentina/day1.jpg",
      type: "image",
      rotation: 8,
      scale: 0.85,
      zIndex: 1,
    },
    {
      id: 69,
      title: "Argentina Crusade Day 2",
      image: "/argentina/day2.jpg",
      type: "image",
      rotation: 0,
      scale: 1,
      zIndex: 30,
    },
    {
      id: 70,
      title: "Argentina Crusade Day 2",
      image: "/argentina/day2-1.jpg",
      type: "image",
      rotation: 0,
      scale: 1,
      zIndex: 30,
    },
    {
      id: 71,
      title: "Argentina Crusae Day 2",
      image: "/argentina/day2-2.jpg",
      type: "image",
      rotation: 0,
      scale: 1,
      zIndex: 30,
    },
    {
      id: 72,
      title: "Argentina Crusade Day 2",
      image: "/argentina/day2-3.jpg",
      type: "image",
      rotation: 0,
      scale: 1,
      zIndex: 30,
    },
    {
      id: 73,
      title: "Argentina Crusade Day 2",
      image: "/argentina/day2-4.jpg",
      type: "image",
      rotation: 0,
      scale: 1,
      zIndex: 30,
    },
    {
      id: 74,
      title: "Argentina Charity Day 3",
      image: "/argentina/day3-1.jpg",
      type: "image",
      rotation: 0,
      scale: 1,
      zIndex: 30,
    },
    {
      id: 75,
      title: "Argentina Charity Day 3",
      image: "/argentina/day3-2.jpg",
      type: "image",
      rotation: 0,
      scale: 1,
      zIndex: 30,
    },
    {
      id: 76,
      title: "Argentina Charity Day 3",
      image: "/argentina/day3-3.jpg",
      type: "image",
      rotation: 0,
      scale: 1,
      zIndex: 30,
    },
    {
      id: 77,
      title: "Argentina Charity Day 3",
      image: "/argentina/day3-4.jpg",
      type: "image",
      rotation: 0,
      scale: 1,
      zIndex: 30,
    },
    {
      id: 78, 
      title: "Argentina Charity Day 3",
      image: "/argentina/day3-5.jpg",
      type: "image",
      rotation: 0,
      scale: 1,
      zIndex: 30,
    },
    {
      id: 79,
      title: "Argentina Charity Day 3",
      image: "/argentina/day3-6.jpg",
      type: "image",
      rotation: 0,
      scale: 1,
      zIndex: 30,
    },
    {
      id: 80,
      title: "Argentina Charity Day 3",
      image: "/argentina/day3-7.jpg",
      type: "image",
      rotation: 0,
      scale: 1,
      zIndex: 30,
    },
    {
      id: 81,
      title: "Argentina Charity Day 3",
      image: "/argentina/day3.jpg",
      type: "image",
      rotation: 0,
      scale: 1,
      zIndex: 30,
    },
  ],
  "Spain": [
    {
      id: 82,
      title: "Spain Crusade",
      image: "/spain/1.jpg",
      type: "image",
      rotation: -6,
      scale: 0.88,
      zIndex: 2,
    },
    {
      id: 83,
      title: "Spain Crusade",
      image: "/spain/2.jpg",
      type: "image",
      rotation: 6,
      scale: 0.87,
      zIndex: 1,
    },
    {
      id: 84,
      title: "Spain Crusade",
      image: "/spain/3.jpg",
      type: "image",
      rotation: 0,
      scale: 1,
      zIndex: 30,
    },
    {
      id: 85,
      title: "Spain Crusade",
      image: "/spain/4.jpg",
      type: "image",
      rotation: 0,
      scale: 1,
      zIndex: 30,
    },
    {
      id: 86,
      title: "Spain Crusade",
      image: "/spain/5.jpg",
      type: "image",
      rotation: 0,
      scale: 1,
      zIndex: 30,
    },
    {
      id: 87,
      title: "Spain Crusade",
      image: "/spain/6.jpg",
      type: "image",
      rotation: 0,
      scale: 1,
      zIndex: 30,
    },
    {
      id: 88,
      title: "Spain Crusade",
      image: "/spain/7.jpg",
      type: "image",
      rotation: 0,
      scale: 1,
      zIndex: 30,
    },
  ],
}

export function GalleryContent() {
  const [activeCategory, setActiveCategory] = useState("SCOAN HQ")

  return (
    <div className="relative max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
      {/* Background image with gradient overlay */}
      <div 
        className="absolute inset-0 z-0 gallery-background opacity-30"
        style={{
          backgroundImage: `url('/bg.jpg')`
        }}
      >
        {/* Multi-layer gradient for better contrast */}
        <div className="absolute inset-0 " />
        <div className="absolute inset-0 " />
        
        {/* Dark mode adjustments */}
        <div className="absolute inset-0 " />
      </div>
      
      {/* Content with higher z-index */}
      <div className="relative z-10">
        <GalleryFilter activeCategory={activeCategory} onCategoryChange={setActiveCategory} />
        <GalleryGrid galleryItems={galleryData[activeCategory] || []} activeCategory={activeCategory} />
        <CategoryDescriptions activeCategory={activeCategory} />
      </div>
    </div>
  )
}