"use client"

import { useState } from "react"
import { GalleryFilter } from "@/components/sections/gallery-filter"
import { GalleryGrid } from "@/components/sections/gallery-grid-enhanced"
import { CategoryDescriptions } from "@/components/sections/gallery-descriptions"

interface GalleryItem {
  id: number
  title: string
  image: string
  type: "image" | "video"
  rotation?: number
  scale?: number
  zIndex?: number
  cloudinaryId?: string // Optional Cloudinary public ID for optimization
}

const galleryData: Record<string, GalleryItem[]> = {
  "SCOAN HQ": [
    {
      id: 0,
      title: "SCOAN Headquarters Service",
      image: "https://res.cloudinary.com/dvlcc2r5w/image/upload/v1770987659/8_nlpxis.jpg",
      type: "image",
      rotation: -8,
      scale: 0.85,
      zIndex: 1,
      cloudinaryId: "8_nlpxis", // Cloudinary public ID for optimization
    },
    {
      id: 1,
      title: "SCOAN Sunday Service",
      image: "https://res.cloudinary.com/dvlcc2r5w/image/upload/v1770987654/2_vcmdoh.jpg",
      type: "image",
      rotation: -4,
      scale: 0.9,
      zIndex: 2,
      cloudinaryId: "2_vcmdoh",
    },
    {
      id: 2,
      title: "SCOAN Sunday Service",
      image: "https://res.cloudinary.com/dvlcc2r5w/image/upload/v1770995712/1_ucalhq.jpg",
      type: "image",
      rotation: 0,
      scale: 1,
      zIndex: 30,
      cloudinaryId: "1_ucalhq",
    },
    {
      id: 3,
      title: "SCOAN Sunday Service",
      image: "https://res.cloudinary.com/dvlcc2r5w/image/upload/v1770996143/3_pksx1q.jpg",
      type: "image",
      rotation: 0,
      scale: 1,
      zIndex: 30,
      cloudinaryId: "3_pksx1q",
    },
  ],
  "Ghana": [
    {
      id: 4,
      title: "Revival Meeting 2025",
      image: "https://res.cloudinary.com/dvlcc2r5w/image/upload/v1770987527/1_k9ljcq.jpg",
      type: "image",
      rotation: 4,
      scale: 0.9,
      zIndex: 3,
      cloudinaryId: "1_k9ljcq.jpg"
    },
    {
      id: 5,
      title: "Revival Meeting 2025",
      image: "https://res.cloudinary.com/dvlcc2r5w/image/upload/v1770987555/2_hoj4zo.jpg",
      type: "image",
      rotation: 8,
      scale: 0.85,
      zIndex: 30,
      cloudinaryId: "2_hoj4zo"
    },
    {
      id: 6,
      title: "Revival Meeting 2025",
      image: "https://res.cloudinary.com/dvlcc2r5w/image/upload/v1770995551/3_ykuia9.jpg",
      type: "image",
      rotation: 8,
      scale: 0.85,
      zIndex: 1,
      cloudinaryId: "3_ykuia9"
    },
    {
      id: 7,
      title: "GHANA CHARITY 2024",
      image: "https://res.cloudinary.com/dvlcc2r5w/image/upload/v1770987627/4_ckvnyy.jpg",
      type: "image",
      rotation: 8,
      scale: 0.85,
      zIndex: 1,
      cloudinaryId: "4_ckvnyy"
    },
    {
      id: 8,
      title: "GHANA CHARITY 2024",
      image: "https://res.cloudinary.com/dvlcc2r5w/image/upload/v1770987635/5_pbseut.jpg",
      type: "image",
      rotation: 8,
      scale: 0.85,
      zIndex: 1,
      cloudinaryId: "5_pbseut"
    },
    {
      id: 9,
      title: "GHANA CHARITY 2024",
      image: "https://res.cloudinary.com/dvlcc2r5w/image/upload/v1770987636/6_chwhha.jpg",
      type: "image",
      rotation: 8,
      scale: 0.85,
      zIndex: 1,
      cloudinaryId: "6_chwhha"
    },
    {
      id: 10, 
      title: "GHANA CHARITY 2024",
      image: "https://res.cloudinary.com/dvlcc2r5w/image/upload/v1770987630/7_bjhpeh.jpg",
      type: "image",
      rotation: 8,
      scale: 0.85,
      zIndex: 1,
      cloudinaryId: "7_bjhpeh",
    },
    {
      id: 11,
      title: "GHANA CHARITY 2024",
      image: "https://res.cloudinary.com/dvlcc2r5w/image/upload/v1770987636/8_jjhegz.jpg",
      type: "image",
      rotation: 8,
      scale: 0.85,
      zIndex: 1,
      cloudinaryId: "8_jjhegz",
    },
    {
      id: 12,
      title: "GHANA CHARITY 2024",
      image: "https://res.cloudinary.com/dvlcc2r5w/image/upload/v1770987559/9_h4dlsk.jpg",
      type: "image",
      rotation: 8,
      scale: 0.85,
      zIndex: 1,
      cloudinaryId: "9_h4dlsk",
    },
    {
      id: 13,
      title: "GHANA CHARITY 2024",
      image: "https://res.cloudinary.com/dvlcc2r5w/image/upload/v1770987558/10_ubgrlk.jpg",
      type: "image",
      rotation: 8,
      scale: 0.85,
      zIndex: 1,
      cloudinaryId: "10_ubgrlk",
    },
    {
      id: 14,
      title: "GHANA CHARITY 2024",
      image: "https://res.cloudinary.com/dvlcc2r5w/image/upload/v1770987551/11_uoyakn.jpg",
      type: "image",
      rotation: 8,
      scale: 0.85,
      zIndex: 1,
      cloudinaryId: "11_uoyakn",
    },
    {
      id: 15,
      title: "GHANA CHARITY 2024",
      image: "https://res.cloudinary.com/dvlcc2r5w/image/upload/v1770987623/12_me1mxc.jpg",
      type: "image",
      rotation: 8,
      scale: 0.85,
      zIndex: 1,
      cloudinaryId: "12_me1mxc",
    },
    {
      id: 16,
      title: "GHANA CHARITY 2024",
      image: "https://res.cloudinary.com/dvlcc2r5w/image/upload/v1770987627/13_d9ke4q.jpg",
      type: "image",
      rotation: 8,
      scale: 0.85,
      zIndex: 1,
      cloudinaryId: "13_d9ke4q",
    },
    {
      id: 17,
      title: "GHANA CHARITY 2024",
      image: "https://res.cloudinary.com/dvlcc2r5w/image/upload/v1770987526/14_rltdse.jpg",
      type: "image",
      rotation: 8,
      scale: 0.85,
      zIndex: 1,
      cloudinaryId: "14_rltdse",
    },
   
    {
      id: 19,
      title: "GHANA CHARITY 2024",
      image: "https://res.cloudinary.com/dvlcc2r5w/image/upload/v1771003962/16_whukhk.jpg",
      type: "image",
      rotation: 8,
      scale: 0.85,
      zIndex: 1,
      cloudinaryId: "16_whukhk",
    },
    {
      id: 20,
      title: "GHANA CHARITY 2024",
      image: "https://res.cloudinary.com/dvlcc2r5w/image/upload/v1770995562/17_ebaio8.jpg",
      type: "image",
      rotation: 8,
      scale: 0.85,
      zIndex: 1,
      cloudinaryId: "17_ebaio8",
    },
    {
      id: 21,
      title: "GHANA CHARITY 2024",
      image: "https://res.cloudinary.com/dvlcc2r5w/image/upload/v1770995565/18_tbiilj.jpg",
      type: "image",
      rotation: 8,
      scale: 0.85,
      zIndex: 1,
      cloudinaryId: "18_tbiilj",
    },
    {
      id: 22,
      title: "GHANA CHARITY 2024",
      image: "https://res.cloudinary.com/dvlcc2r5w/image/upload/v1770995570/19_f5ffge.jpg",
      type: "image",
      rotation: 8,
      scale: 0.85,
      zIndex: 1,
      cloudinaryId: "19_f5ffge",
    },
  ],
  "Kenya": [
    {
      id: 23,
      title: "",
      image: "https://res.cloudinary.com/dvlcc2r5w/image/upload/v1770987507/1_hbzgmy.jpg",
      type: "image",
      rotation: -6,
      scale: 0.88,
      zIndex: 2,
      cloudinaryId: "1_hbzgmy",
    },
    {
      id: 24,
      title: "",
      image: "https://res.cloudinary.com/dvlcc2r5w/image/upload/v1770987508/2_w2i6rt.jpg",
      type: "image",
      rotation: 2,
      scale: 0.92,
      zIndex: 1,
      cloudinaryId: "2_w2i6rt",
    },
    {
      id: 25,
      title: "",
      image: "https://res.cloudinary.com/dvlcc2r5w/image/upload/v1770987517/3_jqb9kj.jpg",
      type: "image",
      rotation: 0,
      scale: 1,
      zIndex: 30,
      cloudinaryId: "3_jqb9kj",
    },
    {
      id: 26,
      title: "",
      image: "https://res.cloudinary.com/dvlcc2r5w/image/upload/v1770987512/4_ukrbxh.jpg",
      type: "image",
      rotation: 0,
      scale: 1,
      zIndex: 30,
      cloudinaryId: "4_ukrbxh",
    },
    {
      id: 27,
      title: "",
      image: "https://res.cloudinary.com/dvlcc2r5w/image/upload/v1770995649/5_xfkcbo.jpg",
      type: "image",
      rotation: 0,
      scale: 1,
      zIndex: 30,
      cloudinaryId: "5_xfkcbo",
    },
    {
      id: 28,
      title: "",
      image: "https://res.cloudinary.com/dvlcc2r5w/image/upload/v1770995647/6_fllizk.jpg",
      type: "image",
      rotation: 0,
      scale: 1,
      zIndex: 30,
      cloudinaryId: "6_fllizk",
    },
    {
      id: 29,
      title: "",
      image: "https://res.cloudinary.com/dvlcc2r5w/image/upload/v1770987571/7_xieanu.jpg",
      type: "image",
      rotation: 0,
      scale: 1,
      zIndex: 30,
      cloudinaryId: "7_xieanu",
    },
    {
      id: 30,
      title: "",
      image: "https://res.cloudinary.com/dvlcc2r5w/image/upload/v1770987571/8_wubpxo.jpg",
      type: "image",
      rotation: 0,
      scale: 1,
      zIndex: 30,
      cloudinaryId: "8_wubpxo",
    },
    {
      id: 31,
      title: "",
      image: "https://res.cloudinary.com/dvlcc2r5w/image/upload/v1770987640/9_zqmno2.jpg",
      type: "image",
      rotation: 0,
      scale: 1,
      zIndex: 30,
      cloudinaryId: "9_zqmno2",
    },
    {
      id: 32,
      title: "",
      image: "https://res.cloudinary.com/dvlcc2r5w/image/upload/v1771005093/10_du6n9i.jpg",
      type: "image",
      rotation: 0,
      scale: 1,
      zIndex: 30,
      cloudinaryId: "10_du6n9i",
    },
    {
      id: 33,
      title: "",
      image: "https://res.cloudinary.com/dvlcc2r5w/image/upload/v1770987557/11_wmz5b1.jpg",
      type: "image",
      rotation: 0,
      scale: 1,
      zIndex: 30,
      cloudinaryId: "11_wmz5b1",
    },
    
    {
      id: 35,
      title: "",
      image: "https://res.cloudinary.com/dvlcc2r5w/image/upload/v1770987557/13_zpcomf.jpg",
      type: "image",
      rotation: 0,
      scale: 1,
      zIndex: 30,
      cloudinaryId: "13_zpcomf",
    },
    
    {
      id: 37, 
      title: "",
      image: "https://res.cloudinary.com/dvlcc2r5w/image/upload/v1770987565/15_mj9ori.jpg",
      type: "image",
      rotation: 0,
      scale: 1,
      zIndex: 30,
      cloudinaryId: "15_mj9ori",
    },
    {
      id: 38,
      title: "",
      image: "https://res.cloudinary.com/dvlcc2r5w/image/upload/v1770987563/16_dhbmyw.jpg",
      type: "image",
      rotation: 0,
      scale: 1,
      zIndex: 30,
      cloudinaryId: "16_dhbmyw",
    },
   
    {
      id: 40,
      title: "",
      image: "https://res.cloudinary.com/dvlcc2r5w/image/upload/v1770987564/18_iumxga.jpg",
      type: "image",
      rotation: 0,
      scale: 1,
      zIndex: 30,
      cloudinaryId: "18_iumxga",
    },
    {
      id: 41,
      title: "",
      image: "https://res.cloudinary.com/dvlcc2r5w/image/upload/v1770987570/19_t8uqzp.jpg",
      type: "image",
      rotation: 0,
      scale: 1,
      zIndex: 30, 
      cloudinaryId: "19_t8uqzp",
    },
  ],
  "Lagos": [
    {
      id: 42,
      title: "",
      image: "https://res.cloudinary.com/dvlcc2r5w/image/upload/v1770987515/1_njjprv.jpg",
      type: "image",
      rotation: -4,
      scale: 0.9,
      zIndex: 3,
      cloudinaryId: "1_njjprv",
    },
    {
      id: 43,
      title: "",
      image: "https://res.cloudinary.com/dvlcc2r5w/image/upload/v1770987583/2_c55ugh.jpg",
      type: "image",
      rotation: 6,
      scale: 0.87,
      zIndex: 1,
      cloudinaryId: "2_c55ugh",
    },
    {
      id: 44,
      title: "",
      image: "https://res.cloudinary.com/dvlcc2r5w/image/upload/v1770987532/3_zehyew.jpg",
      type: "image",
      rotation: 0,
      scale: 1,
      zIndex: 30,
      cloudinaryId: "3_zehyew",
    },
    {
      id: 45,
      title: "",
      image: "https://res.cloudinary.com/dvlcc2r5w/image/upload/v1770987524/4_vrflun.jpg",
      type: "image",
      rotation: 0,
      scale: 1,
      zIndex: 30,
      cloudinaryId: "4_vrflun",
    },
    {
      id: 46,
      title: "",
      image: "https://res.cloudinary.com/dvlcc2r5w/image/upload/v1770987648/5_kjjs5o.jpg",
      type: "image",
      rotation: 0,
      scale: 1,
      zIndex: 30,
      cloudinaryId: "5_kjjs5o",
    },
    {
      id: 47, 
      title: "",
      image: "https://res.cloudinary.com/dvlcc2r5w/image/upload/v1770987529/6_i5ajey.jpg",
      type: "image",
      rotation: 0,
      scale: 1,
      zIndex: 30,
      cloudinaryId: "6_i5ajey",
    },
    {
      id: 48,
      title: "",
      image: "https://res.cloudinary.com/dvlcc2r5w/image/upload/v1770987577/7_e69vub.jpg",
      type: "image",
      rotation: 0,
      scale: 1,
      zIndex: 30,
      cloudinaryId: "7_e69vub",
    },
    {
      id: 49,
      title: "",
      image: "https://res.cloudinary.com/dvlcc2r5w/image/upload/v1770987585/8_pt1vwg.jpg",
      type: "image",
      rotation: 0,
      scale: 1,
      zIndex: 30,
      cloudinaryId: "8_pt1vwg",
    },
   
    {
      id: 51,
      title: "",
      image: "https://res.cloudinary.com/dvlcc2r5w/image/upload/v1770987573/10_vjeohb.jpg",
      type: "image",
      rotation: 0,
      scale: 1,
      zIndex: 30,
      cloudinaryId: "10_vjeohb",
    },
    {
      id: 53,
      title: "",
      image: "https://res.cloudinary.com/dvlcc2r5w/image/upload/v1770987533/12_oe3so5.jpg",
      type: "image",
      rotation: 0,
      scale: 1,
      zIndex: 30,
      cloudinaryId: "12_oe3so5",
    },
  ],
 "South Africa":[
    {
      id: 54,
      title: "",
      image: "https://res.cloudinary.com/dvlcc2r5w/image/upload/v1770996353/1_khxm36.jpg",
      type: "image",
      rotation: -6,
      scale: 0.88,
      zIndex: 2,
      cloudinaryId: "1_khxm36",
    },
    {
      id: 55,
      title: "",
      image: "https://res.cloudinary.com/dvlcc2r5w/image/upload/v1770996311/2_ltwzga.jpg",
      type: "image",
      rotation: 6,
      scale: 0.87,
      zIndex: 1,
      cloudinaryId: "2_ltwzga",
    },
    {
      id: 56,
      title: "",
      image: "https://res.cloudinary.com/dvlcc2r5w/image/upload/v1770996532/3_iztku4.jpg",
      type: "image",
      rotation: 6,
      scale: 0.87,
      zIndex: 1,
      cloudinaryId: "3_iztku4",
    },
    {
      id: 57,
      title: "",
      image: "https://res.cloudinary.com/dvlcc2r5w/image/upload/v1770996426/4_rpygtg.jpg",
      type: "image",
      rotation: 6,
      scale: 0.87,
      zIndex: 1,
      cloudinaryId: "4_rpygtg",
    },
    {
      id: 58,
      title: "",
      image: "https://res.cloudinary.com/dvlcc2r5w/image/upload/v1770987595/5_rip6nk.jpg",
      type: "image",
      rotation: 6,
      scale: 0.87,
      zIndex: 1,
      cloudinaryId: "5_rip6nk",
    },
    {
      id: 59,
      title: "",
      image: "https://res.cloudinary.com/dvlcc2r5w/image/upload/v1770987604/6_o63rgc.jpg",
      type: "image",
      rotation: 6,
      scale: 0.87,
      zIndex: 1,
      cloudinaryId: "6_o63rgc", 
    },
    {
      id: 61,
      title: "",
      image: "https://res.cloudinary.com/dvlcc2r5w/image/upload/v1770987606/8_ybapp1.jpg",
      type: "image",
      rotation: 6,
      scale: 0.87,
      zIndex: 1,
      cloudinaryId: "8_ybapp1",
    },
    {
      id: 62,
      title: "",
      image: "https://res.cloudinary.com/dvlcc2r5w/image/upload/v1770987538/9_tj9ugq.jpg",
      type: "image",
      rotation: 6,
      scale: 0.87,
      zIndex: 1,
      cloudinaryId: "9_tj9ugq",
    },
    {
      id: 63,
      title: "",
      image: "https://res.cloudinary.com/dvlcc2r5w/image/upload/v1770987599/10_lzkr8u.jpg",
      type: "image",
      rotation: 6,
      scale: 0.87,
      zIndex: 1,
      cloudinaryId: "10_lzkr8u",
    },
    {
      id: 64, 
      title: "",
      image: "https://res.cloudinary.com/dvlcc2r5w/image/upload/v1770987593/11_mutrzw.jpg",
      type: "image",
      rotation: 6,
      scale: 0.87,
      zIndex: 1,
      cloudinaryId: "11_mutrzw",
    },
    {
      id: 65,
      title: "",
      image: "https://res.cloudinary.com/dvlcc2r5w/image/upload/v1770987594/12_arvluy.jpg",
      type: "image",
      rotation: 6,
      scale: 0.87,
      zIndex: 1,
      cloudinaryId: "12_arvluy",
    },
   
  ],
  "Argentina": [
    {
      id: 68,
      title: "Argentina Crusade Day 1",
      image: "https://res.cloudinary.com/dvlcc2r5w/image/upload/v1770987612/day1_puwk7s.jpg",
      type: "image",
      rotation: 8,
      scale: 0.85,
      zIndex: 1,
      cloudinaryId: "day1_puwk7s",
    },
    {
      id: 69,
      title: "Argentina Crusade Day 2",
      image: "https://res.cloudinary.com/dvlcc2r5w/image/upload/v1770994675/day2_mglb8t.jpg",
      type: "image",
      rotation: 0,
      scale: 1,
      zIndex: 30,
      cloudinaryId: "day2_mglb8t",
    },
    {
      id: 70,
      title: "Argentina Crusade Day 2",
      image: "https://res.cloudinary.com/dvlcc2r5w/image/upload/v1770994664/day2-1_zjmfhw.jpg",
      type: "image",
      rotation: 0,
      scale: 1,
      zIndex: 30,
      cloudinaryId: "day2-1_zjmfhw",
    },
    {
      id: 71,
      title: "Argentina Crusae Day 2",
      image: "https://res.cloudinary.com/dvlcc2r5w/image/upload/v1770994451/day2-2_efpqin.jpg",
      type: "image",
      rotation: 0,
      scale: 1,
      zIndex: 30,
      cloudinaryId: "day2-2_efpqin",
    },
    {
      id: 72,
      title: "Argentina Crusade Day 2",
      image: "https://res.cloudinary.com/dvlcc2r5w/image/upload/v1770987521/day2-3_cinuol.jpg",
      type: "image",
      rotation: 0,
      scale: 1,
      zIndex: 30,
      cloudinaryId: "day2-3_cinuol",
    },
    {
      id: 73,
      title: "Argentina Crusade Day 2",
      image: "https://res.cloudinary.com/dvlcc2r5w/image/upload/v1770987550/day2-4_xusq46.jpg",
      type: "image",
      rotation: 0,
      scale: 1,
      zIndex: 30,
      cloudinaryId: "day2-4_xusq46",
    },
    {
      id: 74,
      title: "Argentina Charity Day 3",
      image: "https://res.cloudinary.com/dvlcc2r5w/image/upload/v1770994606/day3-1_rshtn1.jpg",
      type: "image",
      rotation: 0,
      scale: 1,
      zIndex: 30,
      cloudinaryId: "day3-1_rshtn1",
    },
    {
      id: 75,
      title: "Argentina Charity Day 3",
      image: "https://res.cloudinary.com/dvlcc2r5w/image/upload/v1770987519/day3-2_ejv9lg.jpg",
      type: "image",
      rotation: 0,
      scale: 1,
      zIndex: 30,
      cloudinaryId: "day3-2_ejv9lg",
    },
    {
      id: 76,
      title: "Argentina Charity Day 3",
      image: "https://res.cloudinary.com/dvlcc2r5w/image/upload/v1770987617/day3-3_coeemj.jpg",
      type: "image",
      rotation: 0,
      scale: 1,
      zIndex: 30,
      cloudinaryId: "day3-3_coeemj",
    },
    {
      id: 77,
      title: "Argentina Charity Day 3",
      image: "https://res.cloudinary.com/dvlcc2r5w/image/upload/v1770987546/day3-4_evqu2x.jpg",
      type: "image",
      rotation: 0,
      scale: 1,
      zIndex: 30,
      cloudinaryId: "day3-4_evqu2x",
    },
    {
      id: 78, 
      title: "Argentina Charity Day 3",
      image: "https://res.cloudinary.com/dvlcc2r5w/image/upload/v1770987615/day3-5_lhntf3.jpg",
      type: "image",
      rotation: 0,
      scale: 1,
      zIndex: 30,
      cloudinaryId: "day3-5_lhntf3",
    },
    {
      id: 79,
      title: "Argentina Charity Day 3",
      image: "https://res.cloudinary.com/dvlcc2r5w/image/upload/v1770987621/day3-6_vhvm7c.jpg",
      type: "image",
      rotation: 0,
      scale: 1,
      zIndex: 30,
      cloudinaryId: "day3-6_vhvm7c",
    },
    {
      id: 80,
      title: "Argentina Charity Day 3",
      image: "https://res.cloudinary.com/dvlcc2r5w/image/upload/v1770994619/day3-7_ohrm6x.jpg",
      type: "image",
      rotation: 0,
      scale: 1,
      zIndex: 30,
      cloudinaryId: "day3-7_ohrm6x",
    },
    {
      id: 81,
      title: "Argentina Charity Day 3",
      image: "https://res.cloudinary.com/dvlcc2r5w/image/upload/v1770994472/day3_jo3sni.jpg",
      type: "image",
      rotation: 0,
      scale: 1,
      zIndex: 30,
      cloudinaryId: "day3_jo3sni",
    },
  ],
  "Spain": [
    {
      id: 82,
      title: "Spain Crusade",
      image: "https://res.cloudinary.com/dvlcc2r5w/image/upload/v1770987606/1_bpbkn5.jpg",
      type: "image",
      rotation: -6,
      scale: 0.88,
      zIndex: 2,
      cloudinaryId: "1_bpbkn5",
    },
    {
      id: 83,
      title: "Spain Crusade",
      image: "https://res.cloudinary.com/dvlcc2r5w/image/upload/v1770987515/2_i6u9eo.jpg",
      type: "image",
      rotation: 6,
      scale: 0.87,
      zIndex: 1,
      cloudinaryId: "2_i6u9eo",
    },
    {
      id: 84,
      title: "Spain Crusade",
      image: "https://res.cloudinary.com/dvlcc2r5w/image/upload/v1770987608/3_gxjsb1.jpg",
      type: "image",
      rotation: 0,
      scale: 1,
      zIndex: 30,
      cloudinaryId: "3_gxjsb1",
    },
    {
      id: 85,
      title: "Spain Crusade",
      image: "https://res.cloudinary.com/dvlcc2r5w/image/upload/v1770987540/4_tpcixc.jpg",
      type: "image",
      rotation: 0,
      scale: 1,
      zIndex: 30,
      cloudinaryId: "4_tpcixc",
    },
    {
      id: 86,
      title: "Spain Crusade",
      image: "https://res.cloudinary.com/dvlcc2r5w/image/upload/v1770987516/5_ca61bz.jpg",
      type: "image",
      rotation: 0,
      scale: 1,
      zIndex: 30,
      cloudinaryId: "5_ca61bz",
    },
    {
      id: 87,
      title: "Spain Crusade",
      image: "https://res.cloudinary.com/dvlcc2r5w/image/upload/v1770987517/6_emkfed.jpg",
      type: "image",
      rotation: 0,
      scale: 1,
      zIndex: 30,
      cloudinaryId: "6_emkfed",
    },
    {
      id: 88,
      title: "Spain Crusade",
      image: "https://res.cloudinary.com/dvlcc2r5w/image/upload/v1770987528/7_ho0kuf.jpg",
      type: "image",
      rotation: 0,
      scale: 1,
      zIndex: 30,
      cloudinaryId: "7_ho0kuf",
    },
  ],
}

export function GalleryContent() {
  const [activeCategory, setActiveCategory] = useState("SCOAN HQ")

  return (
    <div className="relative max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
      {/* Background image with gradient overlay */}
      <div 
        className="absolute inset-0 z-0 gallery-background opacity-30"
        style={{
          backgroundImage: `url('/bg.jpg')`
        }}
      >
        {/* Multi-layer gradient for better contrast */}
        <div className="absolute inset-0 " />
        <div className="absolute inset-0 " />
        
        {/* Dark mode adjustments */}
        <div className="absolute inset-0 " />
      </div>
      
      {/* Content with higher z-index */}
      <div className="relative z-10">
        <GalleryFilter activeCategory={activeCategory} onCategoryChange={setActiveCategory} />
        <GalleryGrid galleryItems={galleryData[activeCategory] || []} activeCategory={activeCategory} />
        <CategoryDescriptions activeCategory={activeCategory} />
      </div>
    </div>
  )
}